### ISSUE TITLE
Burp Import Issue

### ISSUE THREAD

**Issue by calebkinney** [pathetiq/BurpSmartBuster#11]
Good morning! Using Jython2.7 and sys.path.append("/root/jython2.7.0/Lib/site-packages") ... can't seem to get this imported. Thanks! 

```
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importAll(imp.java:1182)
	at nltk.corpus.reader$py.f$0(/root/jython2.7.0/Lib/site-packages/nltk/corpus/reader/__init__.py:111)
	at nltk.corpus.reader$py.call_function(/root/jython2.7.0/Lib/site-packages/nltk/corpus/reader/__init__.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importAll(imp.java:1182)
	at nltk.corpus$py.f$0(/root/jython2.7.0/Lib/site-packages/nltk/corpus/__init__.py:315)
	at nltk.corpus$py.call_function(/root/jython2.7.0/Lib/site-packages/nltk/corpus/__init__.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at nltk.stem.snowball$py.f$0(/root/jython2.7.0/Lib/site-packages/nltk/stem/snowball.py:3642)
	at nltk.stem.snowball$py.call_function(/root/jython2.7.0/Lib/site-packages/nltk/stem/snowball.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at nltk.stem$py.f$0(/root/jython2.7.0/Lib/site-packages/nltk/stem/__init__.py:31)
	at nltk.stem$py.call_function(/root/jython2.7.0/Lib/site-packages/nltk/stem/__init__.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importAll(imp.java:1182)
	at nltk$py.f$0(/root/jython2.7.0/Lib/site-packages/nltk/__init__.py:184)
	at nltk$py.call_function(/root/jython2.7.0/Lib/site-packages/nltk/__init__.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_module_level(imp.java:959)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1081)
	at textblob.blob$py.f$0(/tmp/pycharm-packaging/textblob/textblob/blob.py:690)
	at textblob.blob$py.call_function(/tmp/pycharm-packaging/textblob/textblob/blob.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_module_level(imp.java:959)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at textblob$py.f$0(/tmp/pycharm-packaging/textblob/textblob/__init__.py:11)
	at textblob$py.call_function(/tmp/pycharm-packaging/textblob/textblob/__init__.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_module_level(imp.java:959)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at org.python.pycode._pyx2.f$0(/root/Downloads/BurpSmartBuster/BurpSmartBuster.py:1573)
	at org.python.pycode._pyx2.call_function(/root/Downloads/BurpSmartBuster/BurpSmartBuster.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.odh.<init>(Unknown Source)
	at burp.w6f.a(Unknown Source)
	at burp.n1d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by pathetiq** [comment]
Hi,

Is all package installed like described here? https://github.com/pathetiq/BurpSmartBuster/wiki you can make sure but looking inside your directory for all packages to be installed ("/root/jython2.7.0/Lib/site-packages") 

Also make sure to install those using the pip binary related to the Jython file you use inside burp extender.

Let me know if there anything else.

**Comment by pathetiq** [comment]
Hi @calebkinney ,

Any update? Did you find a solution and if so what was it?

Thanks

**Comment by gavz** [comment]
my steps for install:

java -jar jython_installer-2.7.0.jar

cd /root/jython2.7.0/bin
./pip install beautifulsoup4 requests tld textblob

changes ->  BurpSmartBuster.py : 

sys.path.append("/root/jython2.7.0/Lib/site-packages/")
sys.path.append("/root/jython2.7.0/Lib/site-packages/textblob")
sys.path.append("/root/jython2.7.0/Lib/site-packages/nltk") 

BurpSuite : 

Tab Extender - Tab Options - Python Environment : path /root/jython2.7.0/jpython.jar

**Comment by pathetiq** [comment]
Please see this comment for install steps: https://github.com/pathetiq/BurpSmartBuster/issues/13#issuecomment-254255508

**Comment by pathetiq** [comment]
I update the installation notes and added a fix in the code for the plugin to load correctly. Your issue is related to nltk and textblob version. Your error log isn't full because you copied it from burp output and note a file or the console that's why it was hard to debug.

https://github.com/pathetiq/BurpSmartBuster/commit/23f95bc18c038620e6604d6a7a519fbe4c939b29
https://github.com/pathetiq/BurpSmartBuster/wiki
