### ISSUE TITLE
Error in OS X Cannot create PyString with non-byte value

### ISSUE THREAD

**Issue by AzInstall** [pathetiq/BurpSmartBuster#14]
I believe I have all the required packages installed and the paths are correct, but I get this error in BS when trying to add the extension:

java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
    at org.python.core.PyString.<init>(PyString.java:64)
    at org.python.core.PyString.<init>(PyString.java:70)
    at org.python.core.PySyntaxError.<init>(PySyntaxError.java:33)
    at org.python.core.ParserFacade.fixParseError(ParserFacade.java:95)
    at org.python.core.ParserFacade.parse(ParserFacade.java:190)
    at org.python.core.Py.compile_flags(Py.java:1956)
    at org.python.core.**builtin**.execfile_flags(**builtin**.java:527)
    at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at burp.roe.<init>(Unknown Source)
    at burp.prg.a(Unknown Source)
    at burp.hdc.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)

According to this, it may be a known bug in Jython http://stackoverflow.com/questions/30545083/jython-test-to-prevent-exception-cannot-create-pystring-with-non-byte-value

**Comment by pathetiq** [comment]
Hi @AzInstall thanks for reporting that one. I don't think I will be able to reproduce this because it seems it's a Jython bug and I never had this one on my side or any people I know. 

Also it's seems it's inside PyString which is call by some library I that is not inside my code.

I will try to look it up, but it will take some time. So let me know if you find the exact call that cause the  problem and I'll follow up in a month or before.

**Comment by pathetiq** [comment]
Can't reproduce and seems to be a known Jython bug on OSX or a particular setup. Open a new issue if there's anything else.
