### ISSUE TITLE
I've installed the tld module from requestments, but the plugin installing failed

### ISSUE THREAD

**Issue by d4wner** [pathetiq/BurpSmartBuster#19]
RT, I've installed the tld module from requestments.
Then I tryed to load  tld module in ipython, and it successed.
But when I tried to install the plugin, it made some errors.
By the way, I 've restart the burp for many times.
How could I  solve the problem ?
```
Traceback (most recent call last):
  File "D:\tools\BurpSmartBuster\BurpSmartBuster.py", line 47, in <module>
    from tld import get_tld
ImportError: No module named tld

	at org.python.core.Py.ImportError(Py.java:296)
	at org.python.core.imp.import_first(imp.java:774)
	at org.python.core.imp.import_module_level(imp.java:856)
	at org.python.core.imp.importName(imp.java:936)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1278)
	at org.python.core.PyObject.__call__(PyObject.java:373)
	at org.python.core.__builtin__.__import__(__builtin__.java:1231)
	at org.python.core.imp.importFromAs(imp.java:1030)
	at org.python.core.imp.importFrom(imp.java:1006)
	at org.python.pycode._pyx1.f$0(D:\tools\BurpSmartBuster\BurpSmartBuster.py:1558)
	at org.python.pycode._pyx1.call_function(D:\tools\BurpSmartBuster\BurpSmartBuster.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1302)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:518)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at burp.jie.<init>(Unknown Source)
	at burp.sxf.a(Unknown Source)
	at burp.r5h.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by pathetiq** [comment]
Hi,

You need to install it using the jython 2.7 you download and not python.Though, the easiest way is to install it from the burp store inside burp extender tab. 

Another way would be to run `pip install -r requirements.txt` using the pip from your jython installation.  Or follow instruction from the wiki page.

Let me know if there's anything else.

**Comment by d4wner** [comment]
Hi, 
I'm sure I‘m using jython-standalone-2.7-b1.jar.
And I've seen the Burp store,  this project warns that I should update to a later version to install it.
But I've been at burp version 1.7.11.
Now I'm so confused about it...

**Comment by pathetiq** [comment]
Hi @d4wner,

You must use the file `jython-installer-2.7.0.jar` to install the jython files in a directory and you will find `/path/to/install/jython27/bin/pip` and pip is use to install the component. the standalone version you won't be able to use the pip related to it.

Also burp is now at version 1.7.22. 1.7.11 is from October 2016 so technically your burp can't install the latest version inside burp extender.
