### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by arbazhussain149** [pathetiq/BurpSmartBuster#6]
from tld import get_tld
ImportError: No module named tld

	at org.python.core.Py.ImportError(Py.java:328)
	at org.python.core.imp.import_first(imp.java:877)
	at org.python.core.imp.import_module_level(imp.java:972)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at org.python.pycode._pyx1.f$0(C:\Users\Arbaz Hussain\Desktop\Burp New\Burp New Out of Plugins\BurpSmartBuster-master\BurpSmartBuster.py:1571)
	at org.python.pycode._pyx1.call_function(C:\Users\Arbaz Hussain\Desktop\Burp New\Burp New Out of Plugins\BurpSmartBuster-master\BurpSmartBuster.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at burp.roe.<init>(Unknown Source)
	at burp.prg.a(Unknown Source)
	at burp.hdc.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

i did pip install tld ,

but still didn't worked.

**Comment by pathetiq** [comment]
Hi,

For a temporary fix please try to update the following paths to your computer one:
`sys.path.append("/usr/local/lib/python2.7/site-packages")
sys.path.append("/home/patoff/Documents/Apps/TextBlob")
sys.path.append("/home/patoff/Documents/Apps/nltk")
`

I will work to put code that detect the right path.

Thanks for bringing that up!

**Comment by FreelancePentester** [comment]
Traceback (most recent call last):
  File "/home/ddos/Downloads/BurpSmartBuster/BurpSmartBuster.py", line 41, in <module>
    from tld import get_tld
  File "/usr/local/lib/python2.7/dist-packages/tld/__init__.py", line 9, in <module>
    from tld.utils import get_tld, get_tld_names, update_tld_names, Result
  File "/usr/local/lib/python2.7/dist-packages/tld/utils.py", line 12, in <module>
    from six import PY3
ImportError: No module named six

	at org.python.core.Py.ImportError(Py.java:328)
	at org.python.core.imp.import_first(imp.java:877)
	at org.python.core.imp.import_module_level(imp.java:972)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at tld.utils$py.f$0(/usr/local/lib/python2.7/dist-packages/tld/utils.py:143)
	at tld.utils$py.call_function(/usr/local/lib/python2.7/dist-packages/tld/utils.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromSource(imp.java:396)
	at org.python.core.imp.loadFromSource(imp.java:661)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at tld$py.f$0(/usr/local/lib/python2.7/dist-packages/tld/__init__.py:9)
	at tld$py.call_function(/usr/local/lib/python2.7/dist-packages/tld/__init__.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromSource(imp.java:396)
	at org.python.core.imp.loadFromSource(imp.java:661)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_module_level(imp.java:959)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at org.python.pycode._pyx2.f$0(/home/ddos/Downloads/BurpSmartBuster/BurpSmartBuster.py:1571)
	at org.python.pycode._pyx2.call_function(/home/ddos/Downloads/BurpSmartBuster/BurpSmartBuster.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.roe.<init>(Unknown Source)
	at burp.prg.a(Unknown Source)
	at burp.hdc.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
any help? thanks!

**Comment by pathetiq** [comment]
@FreelancePentester Seems like you are running this in python 3 where it should be python 2.7 and jython 2.7 related to this error:  from six import PY3

Can you try to install tld from pip that comes with jython 2.7 installer and let me know if that works.

Thanks

**Comment by FreelancePentester** [comment]
i am using python 2.7.

**Comment by pathetiq** [comment]
Sorry for the delay, just back from vacation. Any more error details then this stack trace? 

And to make sure:

- You have fix the sys.path.append() to your path where pip installed textblob?
- The jython jar used inside Burp is the same as the one that installed textblob?

**Comment by FreelancePentester** [comment]
of course, i installed it using jython. But i still get this error.

sudo ../jython setup.py install
running install
Checking .pth file support in /home/ddos/jython2.7.0/Lib/site-packages/
/home/ddos/jython2.7.0/bin/jython -E -c pass
TEST PASSED: /home/ddos/jython2.7.0/Lib/site-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing dependency_links to textblob.egg-info/dependency_links.txt
writing top-level names to textblob.egg-info/top_level.txt
writing textblob.egg-info/PKG-INFO
writing requirements to textblob.egg-info/requires.txt
reading manifest file 'textblob.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'textblob.egg-info/SOURCES.txt'
installing library code to build/bdist.java1.8.0_101/egg
running install_lib
running build_py
creating build/bdist.java1.8.0_101/egg
creating build/bdist.java1.8.0_101/egg/textblob
creating build/bdist.java1.8.0_101/egg/textblob/en
copying build/lib/textblob/en/parsers.py -> build/bdist.java1.8.0_101/egg/textblob/en
copying build/lib/textblob/en/sentiments.py -> build/bdist.java1.8.0_101/egg/textblob/en
copying build/lib/textblob/en/en-sentiment.xml -> build/bdist.java1.8.0_101/egg/textblob/en
copying build/lib/textblob/en/en-entities.txt -> build/bdist.java1.8.0_101/egg/textblob/en
copying build/lib/textblob/en/en-context.txt -> build/bdist.java1.8.0_101/egg/textblob/en
copying build/lib/textblob/en/np_extractors.py -> build/bdist.java1.8.0_101/egg/textblob/en
copying build/lib/textblob/en/en-lexicon.txt -> build/bdist.java1.8.0_101/egg/textblob/en
copying build/lib/textblob/en/taggers.py -> build/bdist.java1.8.0_101/egg/textblob/en
copying build/lib/textblob/en/__init__.py -> build/bdist.java1.8.0_101/egg/textblob/en
copying build/lib/textblob/en/en-morphology.txt -> build/bdist.java1.8.0_101/egg/textblob/en
copying build/lib/textblob/en/inflect.py -> build/bdist.java1.8.0_101/egg/textblob/en
copying build/lib/textblob/en/en-spelling.txt -> build/bdist.java1.8.0_101/egg/textblob/en
copying build/lib/textblob/parsers.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/download_corpora.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/classifiers.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/sentiments.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/utils.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/compat.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/wordnet.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/np_extractors.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/blob.py -> build/bdist.java1.8.0_101/egg/textblob
creating build/bdist.java1.8.0_101/egg/textblob/unicodecsv
copying build/lib/textblob/unicodecsv/__init__.py -> build/bdist.java1.8.0_101/egg/textblob/unicodecsv
copying build/lib/textblob/exceptions.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/taggers.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/tokenizers.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/decorators.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/__init__.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/_text.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/inflect.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/translate.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/base.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/mixins.py -> build/bdist.java1.8.0_101/egg/textblob
copying build/lib/textblob/formats.py -> build/bdist.java1.8.0_101/egg/textblob
byte-compiling build/bdist.java1.8.0_101/egg/textblob/en/parsers.py to parsers$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/en/sentiments.py to sentiments$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/en/np_extractors.py to np_extractors$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/en/taggers.py to taggers$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/en/__init__.py to __init__$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/en/inflect.py to inflect$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/parsers.py to parsers$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/download_corpora.py to download_corpora$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/classifiers.py to classifiers$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/sentiments.py to sentiments$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/utils.py to utils$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/compat.py to compat$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/wordnet.py to wordnet$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/np_extractors.py to np_extractors$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/blob.py to blob$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/unicodecsv/__init__.py to __init__$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/exceptions.py to exceptions$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/taggers.py to taggers$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/tokenizers.py to tokenizers$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/decorators.py to decorators$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/__init__.py to __init__$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/_text.py to _text$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/inflect.py to inflect$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/translate.py to translate$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/base.py to base$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/mixins.py to mixins$py.class
byte-compiling build/bdist.java1.8.0_101/egg/textblob/formats.py to formats$py.class
creating build/bdist.java1.8.0_101/egg/EGG-INFO
copying textblob.egg-info/PKG-INFO -> build/bdist.java1.8.0_101/egg/EGG-INFO
copying textblob.egg-info/SOURCES.txt -> build/bdist.java1.8.0_101/egg/EGG-INFO
copying textblob.egg-info/dependency_links.txt -> build/bdist.java1.8.0_101/egg/EGG-INFO
copying textblob.egg-info/not-zip-safe -> build/bdist.java1.8.0_101/egg/EGG-INFO
copying textblob.egg-info/requires.txt -> build/bdist.java1.8.0_101/egg/EGG-INFO
copying textblob.egg-info/top_level.txt -> build/bdist.java1.8.0_101/egg/EGG-INFO
creating 'dist/textblob-0.12.0.dev0-py2.7.egg' and adding 'build/bdist.java1.8.0_101/egg' to it
removing 'build/bdist.java1.8.0_101/egg' (and everything under it)
Processing textblob-0.12.0.dev0-py2.7.egg
removing '/home/ddos/jython2.7.0/Lib/site-packages/textblob-0.12.0.dev0-py2.7.egg' (and everything under it)
creating /home/ddos/jython2.7.0/Lib/site-packages/textblob-0.12.0.dev0-py2.7.egg
Extracting textblob-0.12.0.dev0-py2.7.egg to /home/ddos/jython2.7.0/Lib/site-packages
textblob 0.12.0.dev0 is already the active version in easy-install.pth

Installed /home/ddos/jython2.7.0/Lib/site-packages/textblob-0.12.0.dev0-py2.7.egg
Processing dependencies for textblob==0.12.0.dev0
Searching for nltk==3.2.1
Best match: nltk 3.2.1
Processing nltk-3.2.1-py2.7.egg
nltk 3.2.1 is already the active version in easy-install.pth

Using /home/ddos/jython2.7.0/Lib/site-packages/nltk-3.2.1-py2.7.egg
Finished processing dependencies for textblob==0.12.0.dev0

**Comment by pathetiq** [comment]
Closing issue as no update for a month. Let me know if you made it worked and what was the issue. Thanks

**Comment by pathetiq** [comment]
I update the installation notes and added a fix in the code for the plugin to load correctly. Your issue is related to nltk and textblob version. Your error log isn't full because you copied it from burp output and note a file or the console that's why it was hard to debug.

https://github.com/pathetiq/BurpSmartBuster/commit/23f95bc18c038620e6604d6a7a519fbe4c939b29
https://github.com/pathetiq/BurpSmartBuster/wiki
