### ISSUE TITLE
Load Error : SyntaxError: ("mismatched input 'as' expecting COLON", ('/opt/BurpSmartBuster/BurpSmartBuster.py', 355, 29,

### ISSUE THREAD

**Issue by SatoshiNakamoto** [pathetiq/BurpSmartBuster#8]
Burp Free 1.7.03
Jython 2.5.3 (, Jun 20 2016, 07:22:31) 
[OpenJDK Server VM (Oracle Corporation)] on java1.7.0_91

Error via load:

SyntaxError: ("mismatched input 'as' expecting COLON", ('/opt/BurpSmartBuster/BurpSmartBuster.py', 355, 29, '            except Exception as e:\n'))

	at org.python.core.ParserFacade.fixParseError(ParserFacade.java:92)
	at org.python.core.ParserFacade.parse(ParserFacade.java:186)
	at org.python.core.Py.compile_flags(Py.java:1709)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:514)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at burp.nk.<init>(Unknown Source)
	at burp.atc.a(Unknown Source)
	at burp.n0f.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pathetiq** [comment]
Hi,

Can you try with Jython 2.7 and let me know if that works? And also make sure to install all required modules like described on the [wiki](https://github.com/pathetiq/BurpSmartBuster/wiki).

Thanks

**Comment by SatoshiNakamoto** [comment]
/usr/lib/python2.7/dist-packages/nltk
/usr/local/lib/python2.7/dist-packages/tld
usr/share/javasnoop/lib/TextBlob
root@kali:/usr/share/javasnoop/lib/TextBlob# git branch
* dev
  tag/0.11.1
in wiki error apt-get install python-request (need ...requests)

root@kali:/usr/share/javasnoop/lib/TextBlob# apt-get install python-requests
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-requests is already the newest version (2.10.0-2).
0 upgraded, 0 newly installed, 0 to remove and 1571 not upgraded.
root@kali:/usr/share/javasnoop/lib/TextBlob# apt-get install python-beautifulsoup
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-beautifulsoup is already the newest version (3.2.1-1).
0 upgraded, 0 newly installed, 0 to remove and 1571 not upgraded.

sys.path.append("/usr/local/lib/python2.7/dist-packages")
sys.path.append("/usr/lib/python2.7/dist-packages/")
sys.path.append("/usr/share/javasnoop/lib/TextBlob")

same output

**Comment by SatoshiNakamoto** [comment]
Kali Linux


root@kali:/opt/jython2.7/bin# ./jython 
Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[OpenJDK Server VM (Oracle Corporation)] on java1.7.0_91
Type "help", "copyright", "credits" or "license" for more information.
>>> 
sys.path.append("/usr/local/lib/python2.7/dist-packages")
sys.path.append("/usr/lib/python2.7/dist-packages")
sys.path.append("/opt/jython2.7/bin/TextBlob")

at org.python.antlr.PythonParser.term(PythonParser.java:9855)
	at org.python.antlr.PythonParser.arith_expr(PythonParser.java:9581)
	at org.python.antlr.PythonParser.shift_expr(PythonParser.java:9308)
	at org.python.antlr.PythonParser.and_expr(PythonParser.java:9141)
	at org.python.antlr.PythonParser.xor_expr(PythonParser.java:8978)
	at org.python.antlr.PythonParser.expr(PythonParser.java:8814)
	at org.python.antlr.PythonParser.comparison(PythonParser.java:8360)
	at org.python.antlr.PythonParser.not_test(PythonParser.java:8287)
	at org.python.antlr.PythonParser.and_test(PythonParser.java:8073)
	at org.python.antlr.PythonParser.or_test(PythonParser.java:7911)
	at org.python.antlr.PythonParser.test(PythonParser.java:7771)
	at org.python.antlr.PythonParser.argument(PythonParser.java:13745)
	at org.python.antlr.PythonParser.arglist(PythonParser.java:13364)
	at org.python.antlr.PythonParser.trailer(PythonParser.java:11661)
	at org.python.antlr.PythonParser.power(PythonParser.java:10384)
	at org.python.antlr.PythonParser.factor(PythonParser.java:10290)
	at org.python.antlr.PythonParser.term(PythonParser.java:9855)
	at org.python.antlr.PythonParser.arith_expr(PythonParser.java:9581)
	at org.python.antlr.PythonParser.shift_expr(PythonParser.java:9308)
	at org.python.antlr.PythonParser.and_expr(PythonParser.java:9141)
	at org.python.antlr.PythonParser.xor_expr(PythonParser.java:8978)
	at org.python.antlr.PythonParser.expr(PythonParser.java:8814)
	at org.python.antlr.PythonParser.comparison(PythonParser.java:8360)
	at org.python.antlr.PythonParser.not_test(PythonParser.java:8287)
	at org.python.antlr.PythonParser.and_test(PythonParser.java:8073)
	at org.python.antlr.PythonParser.or_test(PythonParser.java:7911)
	at org.python.antlr.PythonParser.test(PythonParser.java:7771)
	at org.python.antlr.PythonParser.testlist(PythonParser.java:12705)
	at org.python.antlr.PythonParser.expr_stmt(PythonParser.java:3021)
	at org.python.antlr.PythonParser.small_stmt(PythonParser.java:2675)
	at org.python.antlr.PythonParser.simple_stmt(PythonParser.java:2524)
	at org.python.antlr.PythonParser.stmt(PythonParser.java:2438)
	at org.python.antlr.PythonParser.file_input(PythonParser.java:618)
	at org.python.antlr.BaseParser.parseModule(BaseParser.java:78)
	at org.python.core.CompileMode$3.dispatch(CompileMode.java:22)
	at org.python.core.ParserFacade.parse(ParserFacade.java:158)
	at org.python.core.ParserFacade.parse(ParserFacade.java:188)
	at org.python.core.imp.compileSource(imp.java:366)
	at org.python.core.imp.createFromSource(imp.java:388)
	at org.python.core.imp.loadFromSource(imp.java:661)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.ensureFromList(imp.java:1024)
	at org.python.core.imp.ensureFromList(imp.java:992)
	at org.python.core.imp.import_module_level(imp.java:986)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at html5lib.html5parser$py.f$0(/usr/lib/python2.7/dist-packages/html5lib/html5parser.py:2711)
	at html5lib.html5parser$py.call_function(/usr/lib/python2.7/dist-packages/html5lib/html5parser.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_module_level(imp.java:959)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at html5lib$py.f$0(/usr/lib/python2.7/dist-packages/html5lib/__init__.py:23)
	at html5lib$py.call_function(/usr/lib/python2.7/dist-packages/html5lib/__init__.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_first(imp.java:870)
	at org.python.core.imp.import_module_level(imp.java:972)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1081)
	at bs4.builder._html5lib$py.f$0(/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py:325)
	at bs4.builder._html5lib$py.call_function(/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.ensureFromList(imp.java:1024)
	at org.python.core.imp.ensureFromList(imp.java:992)
	at org.python.core.imp.import_module_level(imp.java:986)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at bs4.builder$py.f$0(/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py:324)
	at bs4.builder$py.call_function(/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_module_level(imp.java:959)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at bs4$py.f$0(/usr/lib/python2.7/dist-packages/bs4/__init__.py:468)
	at bs4$py.call_function(/usr/lib/python2.7/dist-packages/bs4/__init__.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_module_level(imp.java:959)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at org.python.pycode._pyx1.f$0(/opt/BurpSmartBuster/BurpSmartBuster.py:1569)
	at org.python.pycode._pyx1.call_function(/opt/BurpSmartBuster/BurpSmartBuster.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at burp.nk.<init>(Unknown Source)
	at burp.atc.a(Unknown Source)
	at burp.n0f.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pathetiq** [comment]
Not sure on that error, can you verify where the nltk and textblob modules are install and which version (really need textblob 0.11.1).

On my side on Kali I did use: sys.path.append("/usr/local/lib/python2.7/site-packages") after installing the module with the pip program under the jython bin directory.

Let me know the path of those 2 modules.

**Comment by pathetiq** [comment]
Closing issue as no update for a month.
