### ISSUE TITLE
ImportError: cannot import name get_tld

### ISSUE THREAD

**Issue by FreelancePentester** [pathetiq/BurpSmartBuster#9]
raceback (most recent call last):
  File "/home/ddos/Downloads/BurpSmartBuster/BurpSmartBuster.py", line 41, in <module>
    from tld import get_tld
ImportError: cannot import name get_tld

	at org.python.core.Py.ImportError(Py.java:328)
	at org.python.core.imp.importFromAs(imp.java:1168)
	at org.python.core.imp.importFrom(imp.java:1132)
	at org.python.pycode._pyx2.f$0(/home/ddos/Downloads/BurpSmartBuster/BurpSmartBuster.py:1571)
	at org.python.pycode._pyx2.call_function(/home/ddos/Downloads/BurpSmartBuster/BurpSmartBuster.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.jk.<init>(Unknown Source)
	at burp.up.a(Unknown Source)
	at burp.wkf.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pathetiq** [comment]
Hi,

Just to make sure did you install [TLD package](https://pypi.python.org/pypi/tld/) with the pip installer that comes with jython 2.7?
if so when you run jython2.7 does the following import works? : 
`from tld import get_tld`

**Comment by FreelancePentester** [comment]
~/jython2.7.0/bin $ java -jar ../jython.jar 
Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_101
Type "help", "copyright", "credits" or "license" for more information.
>>> from tld import get_tld
>>> print get_tld("http://www.google.com")
google.com
>>> print get_tld("http://www.google.com.indod", fail_silently=True)
None
>>>

**Comment by pathetiq** [comment]
If the right path to the libs and the same jython.jar is used inside burp it should work. Make sure that the sys.path.append point to the rights places.

**Comment by FreelancePentester** [comment]
i have a error with textblob

java -jar ../../jython.jar 
Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_101
Type "help", "copyright", "credits" or "license" for more information.
>>> from textblob import TextBlob
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "textblob/__init__.py", line 9, in <module>
    from .blob import TextBlob, Word, Sentence, Blobber, WordList
  File "textblob/blob.py", line 28, in <module>
    import nltk
  File "nltk/__init__.py", line 89, in <module>
    from nltk.internals import config_java
  File "nltk/internals.py", line 28, in <module>
    from nltk import __file__
  File "nltk/nltk/__init__.py", line 89, in <module>
    from nltk.internals import config_java
ImportError: cannot import name config_java

**Comment by FreelancePentester** [comment]
here is my config path:

#sys.path.append("/home/patoff/.local/lib/python2.7/site-packages/")
sys.path.append("/home/ddos/jython2.7.0/Lib/site-packages")
##sys.path.append("/usr/lib/python2.7/dist-packages/")
sys.path.append("/home/ddos/jython2.7.0/Lib/site-packages/textblob")
sys.path.append("/home/ddos/jython2.7.0/Lib/site-packages/nltk")

**Comment by pathetiq** [comment]
I update the installation notes and added a fix in the code for the plugin to load correctly. 

https://github.com/pathetiq/BurpSmartBuster/commit/23f95bc18c038620e6604d6a7a519fbe4c939b29
https://github.com/pathetiq/BurpSmartBuster/wiki
